
spring:
  profiles:
    include: oauth
  datasource:
    url: jdbc:postgresql://localhost:5432/${SCHEMA}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver
    generate-unique-name: false
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
      jakarta:
        persistence:
          sharedCache:
            mode: ALL
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  batch:
    jdbc:
      platform: postgresql